In [30]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [36]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [37]:
x - y

array([-1., -2., -3.])

In [38]:
x * y

array([ 2.,  8., 18.])

In [39]:
x / y

array([0.5, 0.5, 0.5])