# **1.5 Numpy**

1.5.1 Bring Numpy module

In [29]:
import numpy as np

1.5.2 Creating Numpy Array

In [30]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

1.5.3 Arithmetic operand of Numpy 

In [31]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [32]:
x - y

array([-1., -2., -3.])

In [33]:
x * y

array([ 2.,  8., 18.])

In [34]:
x / y

array([0.5, 0.5, 0.5])

In [35]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

1.5.4 N-Dimension Array of Numpy

In [36]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [37]:
A.shape

(2, 2)

In [38]:
A.dtype

dtype('int64')

In [39]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [40]:
# column wise operation -> [[1 * 3, 2 * 0], [3 * 0, 4 * 6]]
A * B

array([[ 3,  0],
       [ 0, 24]])

1.5.5 BroadCast

In [41]:
A * 10

array([[10, 20],
       [30, 40]])

In [42]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
# B -> [[10, 20], [10, 20]] broadcast
A * B

array([[10, 40],
       [30, 80]])

1.5.6 Element Indexing

In [43]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [44]:
X[0]

array([51, 55])

In [45]:
X[0][1]

55

In [50]:
X[:, 1]

array([55, 19,  4])

In [51]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [52]:
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [53]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [54]:
X > 15

array([ True,  True, False,  True, False, False])

In [55]:
X[X > 15]

array([51, 55, 19])