In [ ]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [ ]:
x - y

array([-1., -2., -3.])

In [ ]:
x * y

array([ 2.,  8., 18.])

In [ ]:
x / y

array([0.5, 0.5, 0.5])

In [ ]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [ ]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.shape

(2, 2)

In [ ]:
A.dtype

dtype('int64')

In [ ]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [ ]:
# column wise operation -> [[1 * 3, 2 * 0], [3 * 0, 4 * 6]]
A * B

array([[ 3,  0],
       [ 0, 24]])